#ifndef EXAMPLE_MEMORY_MAP_H
#define EXAMPLE_MEMORY_MAP_H

#include "internalFlash_STM32F205VG.h"

/* Example Memory Map
REGION          START        SIZE           KB   SECTOR(S)
Bootloader      0x08000000   0x00008000     32       0-1
Mftg Params     0x08008000   0x00004000     16       2
User Params     0x0800C000   0x00004000     16       3
Logger Store    0x08010000   0x00010000     64       4
Recovery Img    0x08020000   0x00040000    256       5-6
Application     0x08060000   0x000A0000    640       7-11
*/

/* Internal Flash Map */
#define INTERNAL_FLASH_BOOTLOADER_START          INTERNAL_FLASH_SECTOR0_START_ADDRESS
#define INTERNAL_FLASH_BOOTLOADER_END            INTERNAL_FLASH_SECTOR1_END_ADDRESS

#define INTERNAL_FLASH_MANUFACTURING_START       INTERNAL_FLASH_SECTOR2_START_ADDRESS
#define INTERNAL_FLASH_MANUFACTURING_END         INTERNAL_FLASH_SECTOR2_END_ADDRESS

#define INTERNAL_FLASH_USER_PARAMETERS_START     INTERNAL_FLASH_SECTOR3_START_ADDRESS
#define INTERNAL_FLASH_USER_PARAMETERS_END       INTERNAL_FLASH_SECTOR3_END_ADDRESS

#define INTERNAL_FLASH_DEBUG_LOGGING_START       INTERNAL_FLASH_SECTOR4_START_ADDRESS
#define INTERNAL_FLASH_DEBUG_LOGGING_END         INTERNAL_FLASH_SECTOR4_END_ADDRESS

#define INTERNAL_FLASH_RECOVERY_IMG_START        INTERNAL_FLASH_SECTOR5_START_ADDRESS
#define INTERNAL_FLASH_RECOVERY_IMG_END          INTERNAL_FLASH_SECTOR6_END_ADDRESS

#define INTERNAL_FLASH_APPLICATION_START         INTERNAL_FLASH_SECTOR7_START_ADDRESS
#define INTERNAL_FLASH_APPLICATION_END           INTERNAL_FLASH_SECTOR11_END_ADDRESS

#endif // EXAMPLE_MEMORY_MAP_H
