#ifndef GINGER_EXT_FLASH_MAP_H
#define GINGER_EXT_FLASH_MAP_H

// Update Storage
#define EXT_FLASH_ADDR_UPDATE_STORAGE_START     0x00000000
#define EXT_FLASH_ADDR_UPDATE_STORAGE_END       0x00800000
#define EXT_FLASH_UPDATE_STORAGE_LENGTH         (EXT_FLASH_ADDR_UPDATE_STORAGE_END-EXT_FLASH_ADDR_UPDATE_STORAGE_START)

// Hospitality File
#define EXT_FLASH_ADDR_HOSPITALITY_FILE_START   0x00800000
#define EXT_FLASH_ADDR_HOSPITALITY_FILE_END     0x00801000
#define EXT_FLASH_HOSPITALITY_FILE_LENGTH       (EXT_FLASH_ADDR_HOSPITALITY_FILE_END-EXT_FLASH_ADDR_HOSPITALITY_FILE_START)

// Unused
#define EXT_FLASH_ADDR_UNUSED_START             0x00801000
#define EXT_FLASH_ADDR_UNUSED_END               0x00F00000
#define EXT_FLASH_UNUSED_LENGTH                 (EXT_FLASH_ADDR_UNUSED_END-EXT_FLASH_ADDR_UNUSED_START)

// System Params
#define EXT_FLASH_ADDR_SYS_PARAMS_START         0x00F00000
#define EXT_FLASH_ADDR_SYS_PARAMS_END           0x01000000
#define EXT_FLASH_SYS_PARAMS_LENGTH             (EXT_FLASH_ADDR_SYS_PARAMS_END-EXT_FLASH_ADDR_SYS_PARAMS_START)

#endif // GINGER_EXT_FLASH_MAP_H
