///////////////////////////////////////////////////////////////////////////////
///   @file         internalFlash_STM32F205RE.h
///   @brief
///   @version       $ID: $
///   @author        dj1005472
///   @date          4/1/2016
///   Language:      C
///
///   Description:   Defines specific to STM32F205RE
///
///   Copyright:     (C) 2016 Bose Corporation, Framingham, MA
///
///////////////////////////////////////////////////////////////////////////////

#ifndef INTERNAL_FLASH_STM32F205RE
#define INTERNAL_FLASH_STM32F205RE

#ifndef STM32F205RE
#error STM32F205RE is undefined, wrong memory map is being included
#endif

#define INTERNAL_FLASH_TOTAL_SECTORS             8
#define NUMBER_SMALL_SECTORS                     4
#define NUMBER_MEDIUM_SECTORS                    1
#define NUMBER_LARGE_SECTORS                     3

#define FLASH_SECTOR_IDS FLASH_Sector_0, FLASH_Sector_1, FLASH_Sector_2, FLASH_Sector_3, \
                         FLASH_Sector_4, FLASH_Sector_5, FLASH_Sector_6, FLASH_Sector_7

// There are 3 different sector sizes
#define INTERNAL_FLASH_SECTOR_SIZE_16KB     0x4000         //  16KB
#define INTERNAL_FLASH_SECTOR_SIZE_64KB     0x10000        //  64KB
#define INTERNAL_FLASH_SECTOR_SIZE_128KB    0x20000        // 128KB

#define INTERNAL_FLASH_START_ADDR              0x08000000
#define INTERNAL_FLASH_END_ADDR                0x08080000 // 512KB

// small sectors
#define INTERNAL_FLASH_SECTOR0_START_ADDRESS   INTERNAL_FLASH_START_ADDR
#define INTERNAL_FLASH_SECTOR0_END_ADDRESS     (INTERNAL_FLASH_SECTOR0_START_ADDRESS + INTERNAL_FLASH_SECTOR_SIZE_16KB)

#define INTERNAL_FLASH_SECTOR1_START_ADDRESS   INTERNAL_FLASH_SECTOR0_END_ADDRESS
#define INTERNAL_FLASH_SECTOR1_END_ADDRESS     (INTERNAL_FLASH_SECTOR1_START_ADDRESS + INTERNAL_FLASH_SECTOR_SIZE_16KB)

#define INTERNAL_FLASH_SECTOR2_START_ADDRESS   INTERNAL_FLASH_SECTOR1_END_ADDRESS
#define INTERNAL_FLASH_SECTOR2_END_ADDRESS     (INTERNAL_FLASH_SECTOR2_START_ADDRESS + INTERNAL_FLASH_SECTOR_SIZE_16KB)

#define INTERNAL_FLASH_SECTOR3_START_ADDRESS   INTERNAL_FLASH_SECTOR2_END_ADDRESS
#define INTERNAL_FLASH_SECTOR3_END_ADDRESS     (INTERNAL_FLASH_SECTOR3_START_ADDRESS + INTERNAL_FLASH_SECTOR_SIZE_16KB)

// medium sectors
#define INTERNAL_FLASH_SECTOR4_START_ADDRESS   INTERNAL_FLASH_SECTOR3_END_ADDRESS
#define INTERNAL_FLASH_SECTOR4_END_ADDRESS     (INTERNAL_FLASH_SECTOR4_START_ADDRESS + INTERNAL_FLASH_SECTOR_SIZE_64KB)

// large sectors
#define INTERNAL_FLASH_SECTOR5_START_ADDRESS   INTERNAL_FLASH_SECTOR4_END_ADDRESS
#define INTERNAL_FLASH_SECTOR5_END_ADDRESS     (INTERNAL_FLASH_SECTOR5_START_ADDRESS + INTERNAL_FLASH_SECTOR_SIZE_128KB)

#define INTERNAL_FLASH_SECTOR6_START_ADDRESS   INTERNAL_FLASH_SECTOR5_END_ADDRESS
#define INTERNAL_FLASH_SECTOR6_END_ADDRESS     (INTERNAL_FLASH_SECTOR6_START_ADDRESS + INTERNAL_FLASH_SECTOR_SIZE_128KB)

#define INTERNAL_FLASH_SECTOR7_START_ADDRESS   INTERNAL_FLASH_SECTOR6_END_ADDRESS
#define INTERNAL_FLASH_SECTOR7_END_ADDRESS     (INTERNAL_FLASH_SECTOR7_START_ADDRESS + INTERNAL_FLASH_SECTOR_SIZE_128KB)

// Sector groups
#define NUMBER_SECTOR_GROUPS 3
#define SECTOR_TABLE \
    { \
        INTERNAL_FLASH_SECTOR0_START_ADDRESS, \
        INTERNAL_FLASH_SECTOR3_END_ADDRESS, \
        INTERNAL_FLASH_SECTOR_SIZE_16KB, \
        0, \
        NUMBER_SMALL_SECTORS \
    }, \
    { \
        INTERNAL_FLASH_SECTOR4_START_ADDRESS, \
        INTERNAL_FLASH_SECTOR4_END_ADDRESS, \
        INTERNAL_FLASH_SECTOR_SIZE_64KB, \
        NUMBER_SMALL_SECTORS, \
        NUMBER_MEDIUM_SECTORS, \
    }, \
    { \
        INTERNAL_FLASH_SECTOR5_START_ADDRESS, \
        INTERNAL_FLASH_SECTOR7_END_ADDRESS, \
        INTERNAL_FLASH_SECTOR_SIZE_128KB,  \
        (NUMBER_SMALL_SECTORS + NUMBER_MEDIUM_SECTORS), \
        NUMBER_LARGE_SECTORS \
    }


#endif // INTERNAL_FLASH_STM32F205RE
