#ifndef CEC_H
#define CEC_H

#define BOSE_IEEE_OUI_0 0x08
#define BOSE_IEEE_OUI_1 0xDF
#define BOSE_IEEE_OUI_2 0x1f

#define DEVICE_DISABLED_PHYSICAL_ADDRESS 0xFFFF
#define CEC_MSG_MAX_LEN_BYTES 16
#define CEC_MAX_OSD_LEN 14
#define VENDOR_ID_LEN 3

/* CEC OPCODE */
#define FOR_EACH_CEC_OPCODE(OPCODE) \
    OPCODE(CEC_MESSAGE_FEATURE_ABORT) \
    OPCODE(CEC_0x01) \
    OPCODE(CEC_0x02) \
    OPCODE(CEC_0x03) \
    OPCODE(CEC_MESSAGE_IMAGE_VIEW_ON) \
    OPCODE(CEC_MESSAGE_TUNER_STEP_INC) \
    OPCODE(CEC_MESSAGE_TUNER_STEP_DEC) \
    OPCODE(CEC_MESSAGE_TUNER_DEV_STATUS) \
    OPCODE(CEC_MESSAGE_GIVE_TUNER_DEV_STATUS) \
    OPCODE(CEC_MESSAGE_RECORD_ON) \
    OPCODE(CEC_MESSAGE_RECORD_STATUS) \
    OPCODE(CEC_MESSAGE_RECORD_OFF) \
    OPCODE(CEC_0x0C) \
    OPCODE(CEC_MESSAGE_TEXT_VIEW_ON) \
    OPCODE(CEC_0x0E) \
    OPCODE(CEC_MESSAGE_RECORD_TV_SCREEN) \
    OPCODE(CEC_0x10) \
    OPCODE(CEC_0x11) \
    OPCODE(CEC_0x12) \
    OPCODE(CEC_0x13) \
    OPCODE(CEC_0x14) \
    OPCODE(CEC_0x15) \
    OPCODE(CEC_0x16) \
    OPCODE(CEC_0x17) \
    OPCODE(CEC_0x18) \
    OPCODE(CEC_0x19) \
    OPCODE(CEC_MESSAGE_GIVE_DECK_STATUS) \
    OPCODE(CEC_MESSAGE_DECK_STATUS) \
    OPCODE(CEC_0x1C) \
    OPCODE(CEC_0x1D) \
    OPCODE(CEC_0x1E) \
    OPCODE(CEC_0x1F) \
    OPCODE(CEC_0x20) \
    OPCODE(CEC_0x21) \
    OPCODE(CEC_0x22) \
    OPCODE(CEC_0x23) \
    OPCODE(CEC_0x24) \
    OPCODE(CEC_0x25) \
    OPCODE(CEC_0x26) \
    OPCODE(CEC_0x27) \
    OPCODE(CEC_0x28) \
    OPCODE(CEC_0x29) \
    OPCODE(CEC_0x2A) \
    OPCODE(CEC_0x2B) \
    OPCODE(CEC_0x2C) \
    OPCODE(CEC_0x2D) \
    OPCODE(CEC_0x2E) \
    OPCODE(CEC_0x2F) \
    OPCODE(CEC_0x30) \
    OPCODE(CEC_0x31) \
    OPCODE(CEC_MESSAGE_SET_MENU_LANGUAGE) \
    OPCODE(CEC_MESSAGE_CLR_ANALOGUE_TIMER) \
    OPCODE(CEC_MESSAGE_SET_ANALOGUE_TIMER) \
    OPCODE(CEC_MESSAGE_TIMER_STATUS) \
    OPCODE(CEC_MESSAGE_STANDBY) \
    OPCODE(CEC_0x37) \
    OPCODE(CEC_0x38) \
    OPCODE(CEC_0x39) \
    OPCODE(CEC_0x3A) \
    OPCODE(CEC_0x3B) \
    OPCODE(CEC_0x3C) \
    OPCODE(CEC_0x3D) \
    OPCODE(CEC_0x3E) \
    OPCODE(CEC_0x3F) \
    OPCODE(CEC_0x40) \
    OPCODE(CEC_MESSAGE_PLAY) \
    OPCODE(CEC_MESSAGE_DECK_CONTROL) \
    OPCODE(CEC_MESSAGE_TIMER_CLEARED_STATUS) \
    OPCODE(CEC_MESSAGE_USER_CONTROL_PRESSED) \
    OPCODE(CEC_MESSAGE_USER_CONTROL_RELEASED) \
    OPCODE(CEC_MESSAGE_GIVE_OSD_NAME) \
    OPCODE(CEC_MESSAGE_SET_OSD_NAME) \
    OPCODE(CEC_0x48) \
    OPCODE(CEC_0x49) \
    OPCODE(CEC_0x4A) \
    OPCODE(CEC_0x4B) \
    OPCODE(CEC_0x4C) \
    OPCODE(CEC_0x4D) \
    OPCODE(CEC_0x4E) \
    OPCODE(CEC_0x4F) \
    OPCODE(CEC_0x50) \
    OPCODE(CEC_0x51) \
    OPCODE(CEC_0x52) \
    OPCODE(CEC_0x53) \
    OPCODE(CEC_0x54) \
    OPCODE(CEC_0x55) \
    OPCODE(CEC_0x56) \
    OPCODE(CEC_0x57) \
    OPCODE(CEC_0x58) \
    OPCODE(CEC_0x59) \
    OPCODE(CEC_0x5A) \
    OPCODE(CEC_0x5B) \
    OPCODE(CEC_0x5C) \
    OPCODE(CEC_0x5D) \
    OPCODE(CEC_0x5E) \
    OPCODE(CEC_0x5F) \
    OPCODE(CEC_0x60) \
    OPCODE(CEC_0x61) \
    OPCODE(CEC_0x62) \
    OPCODE(CEC_0x63) \
    OPCODE(CEC_MESSAGE_SET_OSD_STRING) \
    OPCODE(CEC_0x65) \
    OPCODE(CEC_0x66) \
    OPCODE(CEC_MESSAGE_SET_TIMER_PROG_TITLE) \
    OPCODE(CEC_0x68) \
    OPCODE(CEC_0x69) \
    OPCODE(CEC_0x6A) \
    OPCODE(CEC_0x6B) \
    OPCODE(CEC_0x6C) \
    OPCODE(CEC_0x6D) \
    OPCODE(CEC_0x6E) \
    OPCODE(CEC_0x6F) \
    OPCODE(CEC_MESSAGE_SYSTEM_AUDIO_MODE_REQUEST) \
    OPCODE(CEC_MESSAGE_GIVE_AUDIO_STATUS) \
    OPCODE(CEC_MESSAGE_SET_SYSTEM_AUDIO_MODE) \
    OPCODE(CEC_0x73) \
    OPCODE(CEC_0x74) \
    OPCODE(CEC_0x75) \
    OPCODE(CEC_0x76) \
    OPCODE(CEC_0x77) \
    OPCODE(CEC_0x78) \
    OPCODE(CEC_0x79) \
    OPCODE(CEC_MESSAGE_REPORT_AUDIO_STATUS) \
    OPCODE(CEC_0x7B) \
    OPCODE(CEC_0x7C) \
    OPCODE(CEC_MESSAGE_GIVE_SYSTEM_AUDIO_MODE_STATUS) \
    OPCODE(CEC_MESSAGE_SYSTEM_AUDIO_MODE_STATUS) \
    OPCODE(CEC_0x7F) \
    OPCODE(CEC_MESSAGE_ROUTE_CHANGE) \
    OPCODE(CEC_MESSAGE_ROUTE_INFO) \
    OPCODE(CEC_MESSAGE_ACTIVE_SRC) \
    OPCODE(CEC_MESSAGE_GIVE_PHYS_ADDR) \
    OPCODE(CEC_MESSAGE_REPORT_PHYS_ADDR) \
    OPCODE(CEC_MESSAGE_REQ_ACTIVE_SRC) \
    OPCODE(CEC_MESSAGE_SET_STRM_PATH) \
    OPCODE(CEC_MESSAGE_DEVICE_VENDOR_ID) \
    OPCODE(CEC_0x88) \
    OPCODE(CEC_MESSAGE_VENDOR_COMMAND) \
    OPCODE(CEC_MESSAGE_VENDOR_REMOTE_BTN_DOWN) \
    OPCODE(CEC_MESSAGE_VENDOR_REMOTE_BTN_UP) \
    OPCODE(CEC_MESSAGE_GET_VENDOR_ID) \
    OPCODE(CEC_MESSAGE_MENU_REQUEST) \
    OPCODE(CEC_MESSAGE_MENU_STATUS) \
    OPCODE(CEC_MESSAGE_GIVE_PWR_STATUS) \
    OPCODE(CEC_MESSAGE_REPORT_PWR_STATUS) \
    OPCODE(CEC_MESSAGE_GET_MENU_LANGUAGE) \
    OPCODE(CEC_MESSAGE_SEL_ANALOGUE_SERVICE) \
    OPCODE(CEC_MESSAGE_SEL_DIGITAL_SERVICE) \
    OPCODE(CEC_0x94) \
    OPCODE(CEC_0x95) \
    OPCODE(CEC_0x96) \
    OPCODE(CEC_MESSAGE_SET_DIGITAL_TIMER) \
    OPCODE(CEC_0x98) \
    OPCODE(CEC_MESSAGE_CLR_DIGITAL_TIMER) \
    OPCODE(CEC_MESSAGE_SET_AUDIO_RATE) \
    OPCODE(CEC_0x9B) \
    OPCODE(CEC_0x9C) \
    OPCODE(CEC_MESSAGE_INACTIVE_SOURCE) \
    OPCODE(CEC_MESSAGE_CEC_VERSION) \
    OPCODE(CEC_MESSAGE_GET_CEC_VERSION) \
    OPCODE(CEC_MESSAGE_VENDOR_CMD_WITH_ID) \
    OPCODE(CEC_MESSAGE_CLR_EXTERNAL_TIMER) \
    OPCODE(CEC_MESSAGE_SET_EXTERNAL_TIMER) \
    OPCODE(CEC_MESSAGE_REPORT_SHORT_AUDIO_DESCRIPTOR) \
    OPCODE(CEC_MESSAGE_REQUEST_SHORT_AUDIO_DESCRIPTOR) \
    OPCODE(CEC_0xA5) \
    OPCODE(CEC_0xA6) \
    OPCODE(CEC_0xA7) \
    OPCODE(CEC_0xA8) \
    OPCODE(CEC_0xA9) \
    OPCODE(CEC_0xAA) \
    OPCODE(CEC_0xAB) \
    OPCODE(CEC_0xAC) \
    OPCODE(CEC_0xAD) \
    OPCODE(CEC_0xAE) \
    OPCODE(CEC_0xAF) \
    OPCODE(CEC_0xB0) \
    OPCODE(CEC_0xB1) \
    OPCODE(CEC_0xB2) \
    OPCODE(CEC_0xB3) \
    OPCODE(CEC_0xB4) \
    OPCODE(CEC_0xB5) \
    OPCODE(CEC_0xB6) \
    OPCODE(CEC_0xB7) \
    OPCODE(CEC_0xB8) \
    OPCODE(CEC_0xB9) \
    OPCODE(CEC_0xBA) \
    OPCODE(CEC_0xBB) \
    OPCODE(CEC_0xBC) \
    OPCODE(CEC_0xBD) \
    OPCODE(CEC_0xBE) \
    OPCODE(CEC_0xBF) \
    OPCODE(CEC_MESSAGE_INITIATE_ARC) \
    OPCODE(CEC_MESSAGE_REPORT_ARC_INITIATED) \
    OPCODE(CEC_MESSAGE_REPORT_ARC_TERMINATED) \
    OPCODE(CEC_MESSAGE_REQUEST_ARC_INITIATION) \
    OPCODE(CEC_MESSAGE_REQUEST_ARC_TERMINATION) \
    OPCODE(CEC_MESSAGE_TERMINATE_ARC) \
    OPCODE(CEC_0xC6) \
    OPCODE(CEC_0xC7) \
    OPCODE(CEC_0xC8) \
    OPCODE(CEC_0xC9) \
    OPCODE(CEC_0xCA) \
    OPCODE(CEC_0xCB) \
    OPCODE(CEC_0xCC) \
    OPCODE(CEC_0xCD) \
    OPCODE(CEC_0xCE) \
    OPCODE(CEC_0xCF) \
    OPCODE(CEC_0xD0) \
    OPCODE(CEC_0xD1) \
    OPCODE(CEC_0xD2) \
    OPCODE(CEC_0xD3) \
    OPCODE(CEC_0xD4) \
    OPCODE(CEC_0xD5) \
    OPCODE(CEC_0xD6) \
    OPCODE(CEC_0xD7) \
    OPCODE(CEC_0xD8) \
    OPCODE(CEC_0xD9) \
    OPCODE(CEC_0xDA) \
    OPCODE(CEC_0xDB) \
    OPCODE(CEC_0xDC) \
    OPCODE(CEC_0xDD) \
    OPCODE(CEC_0xDE) \
    OPCODE(CEC_0xDF) \
    OPCODE(CEC_0xE0) \
    OPCODE(CEC_0xE1) \
    OPCODE(CEC_0xE2) \
    OPCODE(CEC_0xE3) \
    OPCODE(CEC_0xE4) \
    OPCODE(CEC_0xE5) \
    OPCODE(CEC_0xE6) \
    OPCODE(CEC_0xE7) \
    OPCODE(CEC_0xE8) \
    OPCODE(CEC_0xE9) \
    OPCODE(CEC_0xEA) \
    OPCODE(CEC_0xEB) \
    OPCODE(CEC_0xEC) \
    OPCODE(CEC_0xED) \
    OPCODE(CEC_0xEE) \
    OPCODE(CEC_0xEF) \
    OPCODE(CEC_0xF0) \
    OPCODE(CEC_0xF1) \
    OPCODE(CEC_0xF2) \
    OPCODE(CEC_0xF3) \
    OPCODE(CEC_0xF4) \
    OPCODE(CEC_0xF5) \
    OPCODE(CEC_0xF6) \
    OPCODE(CEC_0xF7) \
    OPCODE(CEC_MESSAGE_CDC_MESSAGE) \
    OPCODE(CEC_0xF9) \
    OPCODE(CEC_0xFA) \
    OPCODE(CEC_0xFB) \
    OPCODE(CEC_0xFC) \
    OPCODE(CEC_0xFD) \
    OPCODE(CEC_0xFE) \
    OPCODE(CEC_MESSAGE_ABORT) \

#define GENERATE_OP_STRING(STRING) #STRING,
#define GENERATE_OP(CODE) CODE,

typedef enum
{
    FOR_EACH_CEC_OPCODE (GENERATE_OP)
} CEC_OpCode;

#define CEC_POWER_STATUS_ON            0
#define CEC_POWER_STATUS_STNDBY        1
#define CEC_POWER_STATUS_TURNINGON     2
#define CEC_POWER_STATUS_TURNINGOFF    3

/* CEC Feature Abort Reason */
#define CEC_ABRT_UNRECOGNIZED_OPCODE   0
#define CEC_ABRT_NOT_IN_CORRECT_MODE   1
#define CEC_ABRT_CANNOT_PROVIDE_SOURCE 2
#define CEC_ABRT_INVALID_OPERAND       3
#define CEC_ABRT_REFUSED               4
#define CEC_ABRT_UNABLE_TO_DETERMINE   5

#define SR_DST_INDEX 0
#define OPCODE_INDEX 1
#define ADDR1_INDEX  2
#define ADDR2_INDEX  4
#define UI_KEY_INDEX 2
#define VOLUME_MUTE_INDEX 2
#define ROUTE_CHANGE_LEN 6
#define ROUTE_INFO_LEN 4


typedef enum
{
    CEC_VERSION_UNKNOWN    = 0xFF,
    CEC_VERSION_13A        = 0x04,
    CEC_VERSION_14         = 0x05,
    CEC_VERSION_20         = 0x06,
} CEC_VERSION;

typedef enum
{
    CEC_DEVICE_TV          = 0x00,
    CEC_DEVICE_RECORDER_1  = 0x01,
    CEC_DEVICE_RECORDER_2  = 0x02,
    CEC_DEVICE_TUNER_1     = 0x03,
    CEC_DEVICE_PLAYBACK_1  = 0x04,
    CEC_DEVICE_AUDIO       = 0x05,
    CEC_DEVICE_TUNER_2     = 0x06,
    CEC_DEVICE_TUNER_3     = 0x07,
    CEC_DEVICE_PLAYBACK_2  = 0x08,
    CEC_DEVICE_RECORDER_3  = 0x09,
    CEC_DEVICE_TUNER_4     = 0x0A,
    CEC_DEVICE_PLAYBACK_3  = 0x0B,
    CEC_DEVICE_FREE_USE    = 0x0E,
    CEC_DEVICE_UNREG_BCAST = 0x0F,
    CEC_DEVICE_NUM_DEVICES = 0x0F,
    CEC_DEVICE_DISABLED    = 0xFF,
} CEC_DEVICES;

#endif // CEC_H