#ifndef CEC_KEY_INDEX_H
#define CEC_KEY_INDEX_H

#include "KeyData.h"

typedef enum
{
    CEC_KEY_PRESS = 0x44,
    CEC_KEY_RELEASE = 0x45
} CEC_KEY_STATE;

typedef enum
{
    CEC_UCC_SELECT = 0x00,
    CEC_UCC_UP = 0x01,
    CEC_UCC_DOWN = 0x02,
    CEC_UCC_LEFT = 0x03,
    CEC_UCC_RIGHT = 0x04,
    CEC_UCC_RIGHT_UP = 0x05,
    CEC_UCC_RIGHT_DOWN = 0x06,
    CEC_UCC_LEFT_UP = 0x07,
    CEC_UCC_LEFT_DOWN = 0x08,
    CEC_UCC_ROOT_MENU = 0x09,
    CEC_UCC_SETUP_MENU = 0x0A,
    CEC_UCC_CONTENTS_MENU = 0x0B,
    CEC_UCC_FAVORITE_MENU = 0x0C,
    CEC_UCC_EXIT = 0x0D,
    CEC_UCC_RESERVED14 = 0x0E,
    CEC_UCC_RESERVED15 = 0x0F,
    CEC_UCC_RESERVED16 = 0x10,
    CEC_UCC_RESERVED17 = 0x11,
    CEC_UCC_RESERVED18 = 0x12,
    CEC_UCC_RESERVED19 = 0x13,
    CEC_UCC_RESERVED20 = 0x14,
    CEC_UCC_RESERVED21 = 0x15,
    CEC_UCC_RESERVED22 = 0x16,
    CEC_UCC_RESERVED23 = 0x17,
    CEC_UCC_RESERVED24 = 0x18,
    CEC_UCC_RESERVED25 = 0x19,
    CEC_UCC_RESERVED26 = 0x1A,
    CEC_UCC_RESERVED27 = 0x1B,
    CEC_UCC_RESERVED28 = 0x1C,
    CEC_UCC_RESERVED29 = 0x1D,
    CEC_UCC_RESERVED30 = 0x1E,
    CEC_UCC_RESERVED31 = 0x1F,
    CEC_UCC_0 = 0x20,
    CEC_UCC_1 = 0x21,
    CEC_UCC_2 = 0x22,
    CEC_UCC_3 = 0x23,
    CEC_UCC_4 = 0x24,
    CEC_UCC_5 = 0x25,
    CEC_UCC_6 = 0x26,
    CEC_UCC_7 = 0x27,
    CEC_UCC_8 = 0x28,
    CEC_UCC_9 = 0x29,
    CEC_UCC_DOT = 0x2A,
    CEC_UCC_ENTER = 0x2B,
    CEC_UCC_CLEAR = 0x2C,
    CEC_UCC_RESERVED45 = 0x2D,
    CEC_UCC_RESERVED46 = 0x2E,
    CEC_UCC_NEXT_FAVORITE = 0x2F,
    CEC_UCC_CHANNEL_UP = 0x30,
    CEC_UCC_CHANNEL_DOWN = 0x31,
    CEC_UCC_PREVIOUS_CHANNEL = 0x32,
    CEC_UCC_SOUND_SELECT = 0x33,
    CEC_UCC_INPUT_SELECT = 0x34,
    CEC_UCC_DISPLAY_INFORMATION = 0x35,
    CEC_UCC_HELP = 0x36,
    CEC_UCC_PAGE_UP = 0x37,
    CEC_UCC_PAGE_DOWN = 0x38,
    CEC_UCC_RESERVED57 = 0x39,
    CEC_UCC_RESERVED58 = 0x3A,
    CEC_UCC_RESERVED59 = 0x3B,
    CEC_UCC_RESERVED60 = 0x3C,
    CEC_UCC_RESERVED61 = 0x3D,
    CEC_UCC_RESERVED62 = 0x3E,
    CEC_UCC_RESERVED63 = 0x3F,
    CEC_UCC_POWER = 0x40,
    CEC_UCC_VOLUME_UP = 0x41,
    CEC_UCC_VOLUME_DOWN = 0x42,
    CEC_UCC_MUTE = 0x43,
    CEC_UCC_PLAY = 0x44,
    CEC_UCC_STOP = 0x45,
    CEC_UCC_PAUSE = 0x46,
    CEC_UCC_RECORD = 0x47,
    CEC_UCC_REWIND = 0x48,
    CEC_UCC_FAST_FORWARD = 0x49,
    CEC_UCC_EJECT = 0x4A,
    CEC_UCC_FORWARD = 0x4B,
    CEC_UCC_BACKWARD = 0x4C,
    CEC_UCC_STOP_RECORD = 0x4D,
    CEC_UCC_PAUSE_RECORD = 0x4E,
    CEC_UCC_RESERVED79 = 0x4F,
    CEC_UCC_ANGLE = 0x50,
    CEC_UCC_SUB_PICTURE = 0x51,
    CEC_UCC_VIDEO_ON_DEMAND = 0x52,
    CEC_UCC_ELECTRONIC_PRORAM_GUIDE = 0x53,
    CEC_UCC_TIMER_PROGRAMMING = 0x54,
    CEC_UCC_INITAL_CONFIGURATION = 0x55,
    CEC_UCC_RESERVED80 = 0x56,
    CEC_UCC_RESERVED81 = 0x57,
    CEC_UCC_RESERVED82 = 0x58,
    CEC_UCC_RESERVED83 = 0x59,
    CEC_UCC_RESERVED84 = 0x5A,
    CEC_UCC_RESERVED85 = 0x5B,
    CEC_UCC_RESERVED86 = 0x5C,
    CEC_UCC_RESERVED87 = 0x5D,
    CEC_UCC_RESERVED88 = 0x5E,
    CEC_UCC_RESERVED89 = 0x5F,
    CEC_UCC_PLAY_FUNCTION = 0x60,
    CEC_UCC_PAUSE_PLAY_FUNCTION = 0x61,
    CEC_UCC_RECORD_FUNCTION = 0x62,
    CEC_UCC_PAUSE_RECORD_FUNCTION = 0x63,
    CEC_UCC_STOP_FUNCTION = 0x64,
    CEC_UCC_MUTE_FUNCTION = 0x65,
    CEC_UCC_RESTORE_VOLUME_FUNCTION = 0x66,
    CEC_UCC_TUNE_FUNCTION = 0x67,
    CEC_UCC_SELECT_TUNE_FUNCTION = 0x68,
    CEC_UCC_SELECT_AV_INPUT_FUNCTION = 0x69,
    CEC_UCC_SELECT_AUDIO_INPUT_FUNCTION = 0x6A,
    CEC_UCC_POWER_TOGGLE_FUNCTION = 0x6B,
    CEC_UCC_POWER_OFF_FUNCTION = 0x6C,
    CEC_UCC_POWER_ON_FUNCTION = 0x6D,
    CEC_UCC_RESERVED110 = 0x6E,
    CEC_UCC_RESERVED111 = 0x6F,
    CEC_UCC_RESERVED112 = 0x70,
    CEC_UCC_F1_BLUE = 0x71,
    CEC_UCC_F2_RED = 0x72,
    CEC_UCC_F3_GREEN = 0x73,
    CEC_UCC_F4_YELLOW = 0x74,
    CEC_UCC_F5 = 0x75,
    CEC_UCC_DATA = 0x76,
    CEC_UCC_NUM,
    CEC_UCC_INVALID = 0xFF
                      /* 0x77 - 0xFF RESERVED */
} CEC_USER_CONTROL_CODE;

static const CEC_USER_CONTROL_CODE CEC_BOSE_KEY_MAPPING[] =
{
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_00,           // 0x00
    CEC_UCC_INVALID,  // BOSE_MUTE,                  // 0x01
    CEC_UCC_INVALID,  // BOSE_VOLUME_DOWN,           // 0x02
    CEC_UCC_INVALID,  // BOSE_VOLUME_UP,             // 0x03
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_04,           // 0x04
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_05,           // 0x05
    CEC_UCC_INVALID,  // BOSE_GAME_SOURCE,           // 0x06
    CEC_UCC_INVALID,  // BOSE_SPECIAL_FEATURE_2,     // 0x07
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_08,           // 0x08
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_09,           // 0x09
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_0A,           // 0x0A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_0B,           // 0x0B
    CEC_UCC_INVALID,  // BOSE_SPECIAL_FEATURE_1,     // 0x0C
    CEC_UCC_INVALID,  // BOSE_AUX_SOURCE,            // 0x0D
    CEC_UCC_INVALID,  // BOSE_TV_SOURCE,             // 0x0E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_0F,           // 0x0F

    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_10,           // 0x10
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_11,           // 0x11
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_12,           // 0x12
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_13,           // 0x13
    CEC_UCC_PREVIOUS_CHANNEL,  // BOSE_LAST_CHANNEL,          // 0x14
    CEC_UCC_INVALID,  // BOSE_CBL_SAT_SOURCE,        // 0x15
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_16,           // 0x16
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_17,           // 0x17
    CEC_UCC_CHANNEL_DOWN,  // BOSE_CHANNEL_PRESET_DOWN,   // 0x18
    CEC_UCC_CHANNEL_UP,  // BOSE_CHANNEL_PRESET_UP,     // 0x19
    CEC_UCC_STOP,  // BOSE_STOP,                  // 0x1A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_1B,           // 0x1B
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_1C,           // 0x1C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_1D,           // 0x1D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_1E,           // 0x1E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_1F,           // 0x1F

    CEC_UCC_DOWN,  // BOSE_DOWN_ARROW,            // 0x20
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_21,           // 0x21
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_22,           // 0x22
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_23,           // 0x23
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_24,           // 0x24
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_25,           // 0x25
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_26,           // 0x26
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_27,           // 0x27
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_28,           // 0x28
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_29,           // 0x29
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_2A,           // 0x2A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_2B,           // 0x2B
    CEC_UCC_POWER,  // BOSE_SOURCE_POWER,          // 0x2C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_2D,           // 0x2D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_2E,           // 0x2E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_2F,           // 0x2F

    CEC_UCC_EXIT,  // BOSE_EXIT,                  // 0x30
    CEC_UCC_INVALID,  // BOSE_MENU_EXIT,             // 0x31
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_32,           // 0x32
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_33,           // 0x33
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_34,           // 0x34
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_35,           // 0x35
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_36,           // 0x36
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_37,           // 0x37
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_38,           // 0x38
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_39,           // 0x39
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_3A,           // 0x3A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_3B,           // 0x3B
    CEC_UCC_SELECT_AV_INPUT_FUNCTION,  // BOSE_TV_INPUT,              // 0x3C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_3D,           // 0x3D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_3E,           // 0x3E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_3F,           // 0x3F

    CEC_UCC_0,  // BOSE_NUMBER_0,              // 0x40
    CEC_UCC_1,  // BOSE_NUMBER_1,              // 0x41
    CEC_UCC_2,  // BOSE_NUMBER_2,              // 0x42
    CEC_UCC_3,  // BOSE_NUMBER_3,              // 0x43
    CEC_UCC_4,  // BOSE_NUMBER_4,              // 0x44
    CEC_UCC_5,  // BOSE_NUMBER_5,              // 0x45
    CEC_UCC_6,  // BOSE_NUMBER_6,              // 0x46
    CEC_UCC_7,  // BOSE_NUMBER_7,              // 0x47
    CEC_UCC_8,  // BOSE_NUMBER_8,              // 0x48
    CEC_UCC_9,  // BOSE_NUMBER_9,              // 0x49
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_4A,           // 0x4A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_4B,           // 0x4B
    CEC_UCC_INVALID,  // BOSE_ON_OFF,                // 0x4C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_4D,           // 0x4D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_4E,           // 0x4E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_4F,           // 0x4F

    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_50,           // 0x50
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_51,           // 0x51
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_,             // 0x52
    CEC_UCC_INVALID,  // BOSE_BD_DVD_SOURCE,         // 0x53
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_54,           // 0x54
    CEC_UCC_PLAY,  // BOSE_PLAY,                  // 0x55
    CEC_UCC_PAUSE,  // BOSE_PAUSE,                 // 0x56
    CEC_UCC_REWIND,  // BOSE_FAST_REVERSE,          // 0x57
    CEC_UCC_FAST_FORWARD,  // BOSE_FAST_FORWARD,          // 0x58
    CEC_UCC_BACKWARD,  // BOSE_QUICK_REPLAY,          // 0x59
    CEC_UCC_FORWARD,  // BOSE_QUICK_SKIP,            // 0x5A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_5B,           // 0x5B
    CEC_UCC_DOT,  // BOSE_DASH,                  // 0x5C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_5D,           // 0x5D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_5E,           // 0x5E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_5F,           // 0x5F

    CEC_UCC_RIGHT,  // BOSE_RIGHT_ARROW,           // 0x60
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_61,           // 0x61
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_62,           // 0x62
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_63,           // 0x63
    CEC_UCC_DISPLAY_INFORMATION,  // BOSE_INFO,                  // 0x64
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_65,           // 0x65
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_66,           // 0x66
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_67,           // 0x67
    CEC_UCC_PAGE_DOWN,  // BOSE_PAGE_DOWN,             // 0x68
    CEC_UCC_PAGE_UP,  // BOSE_PAGE_UP,               // 0x69
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_6A,           // 0x6A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_6B,           // 0x6B
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_6C,           // 0x6C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_6D,           // 0x6D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_6E,           // 0x6E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_6F,           // 0x6F

    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_70,           // 0x70
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_71,           // 0x71
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_72,           // 0x72
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_73,           // 0x73
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_74,           // 0x74
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_75,           // 0x75
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_76,           // 0x76
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_77,           // 0x77
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_78,           // 0x78
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_79,           // 0x79
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_7A,           // 0x7A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_7B,           // 0x7B
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_7C,           // 0x7C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_7D,           // 0x7D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_7E,           // 0x7E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_7F,           // 0x7F

    CEC_UCC_INVALID,  // BOSE_SYSTEM,                // 0x80
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_81,           // 0x81
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_82,           // 0x82
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_83,           // 0x83
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_84,           // 0x84
    CEC_UCC_FAVORITE_MENU,    // BOSE_MORE_SOFTKEY_FAVORITE, // 0x85
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_86,           // 0x86
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_87,           // 0x87
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_88,           // 0x88
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_89,           // 0x89
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_8A,           // 0x8A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_8B,           // 0x8B
    CEC_UCC_INVALID,  // BOSE_ASSERT_ON,             // 0x8C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_8D,           // 0x8D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_8E,           // 0x8E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_8F,           // 0x8F

    CEC_UCC_CONTENTS_MENU,  // BOSE_DVD_MENU,              // 0x90
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_91,           // 0x91
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_92,           // 0x92
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_93,           // 0x93
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_94,           // 0x94
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_95,           // 0x95
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_96,           // 0x96
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_97,           // 0x97
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_98,           // 0x98
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_99,           // 0x99
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_9A,           // 0x9A
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_9B,           // 0x9B
    CEC_UCC_RECORD,  // BOSE_RECORD,                // 0x9C
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_9D,           // 0x9D
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_9E,           // 0x9E
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_9F,           // 0x9F

    CEC_UCC_LEFT,  // BOSE_LEFT_ARROW,            // 0xA0
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A1,           // 0xA1
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A2,           // 0xA2
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A3,           // 0xA3
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A4,           // 0xA4
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A5,           // 0xA5
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A6,           // 0xA6
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A7,           // 0xA7
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A8,           // 0xA8
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_A9,           // 0xA9
    CEC_UCC_POWER,    // BOSE_MORE_SOFTKEY_PWRTOGGLE,// 0xAA
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_AB,           // 0xAB
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_AC,           // 0xAC
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_AD,           // 0xAD
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_AE,           // 0xAE
    CEC_UCC_ROOT_MENU,   // BOSE_INTERNET,           // 0xAF

    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_B0,           // 0xB0
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_B1,           // 0xB1
    CEC_UCC_SUB_PICTURE,  // BOSE_CLOSED_CAPTION,        // 0xB2
    CEC_UCC_INVALID,  // BOSE_SOUND_TOUCH,           // 0xB3
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_B4,           // 0xB4
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_B5,           // 0xB5
    CEC_UCC_SETUP_MENU,  // BOSE_DVR,                   // 0xB6
    CEC_UCC_DATA,  // BOSE_TELETEXT,              // 0xB7
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_B8,           // 0xB8
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_B9,           // 0xB9
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_BA,           // 0xBA
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_BB,           // 0xBB
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_BC,           // 0xBC
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_BD,           // 0xBD
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_BE,           // 0xBE
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_BF,           // 0xBF

    CEC_UCC_UP,  // BOSE_UP_ARROW,              // 0xC0
    CEC_UCC_ROOT_MENU,  // BOSE_I_TV,                  // 0xC1
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_C2,           // 0xC2
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_C3,           // 0xC3
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_C4,           // 0xC4
    CEC_UCC_F2_RED,  // BOSE_RED,                   // 0xC5
    CEC_UCC_F3_GREEN,  // BOSE_GREEN,                 // 0xC6
    CEC_UCC_F4_YELLOW,  // BOSE_YELLOW,                // 0xC7
    CEC_UCC_F1_BLUE,  // BOSE_BLUE,                  // 0xC8
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_C9,           // 0xC9
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_CA,           // 0xCA
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_CB,           // 0xCB
    CEC_UCC_INVALID,  // BOSE_ASSERT_OFF,            // 0xCC
    CEC_UCC_INVALID,  // BOSE_ASSERT_UNMUTE,         // 0xCD
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_CE,           // 0xCE
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_CF,           // 0xCF

    CEC_UCC_ELECTRONIC_PRORAM_GUIDE,  // BOSE_EPG,                   // 0xD0
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D1,           // 0xD1
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D2,           // 0xD2
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D3,           // 0xD3
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D4,           // 0xD4
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D5,           // 0xD5
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D6,           // 0xD6
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D7,           // 0xD7
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D8,           // 0xD8
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_D9,           // 0xD9
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_DA,           // 0xDA
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_DB,           // 0xDB
    CEC_UCC_INVALID,  // BOSE_ASPECT_RATIO,          // 0xDC
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_DD,           // 0xDD
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_DE,           // 0xDE
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_DF,           // 0xDF

    CEC_UCC_SELECT,  // BOSE_ENTER,                 // 0xE0
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E1,           // 0xE1
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E2,           // 0xE2
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E3,           // 0xE3
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E4,           // 0xE4
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E5,           // 0xE5
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E6,           // 0xE6
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E7,           // 0xE7
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E8,           // 0xE8
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_E9,           // 0xE9
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_EA,           // 0xEA
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_EB,           // 0xEB
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_EC,           // 0xEC
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_ED,           // 0xED
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_EE,           // 0xEE
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_EF,           // 0xEF

    CEC_UCC_INVALID,  // BOSE_SPECIAL_FEATURE_3,     // 0xF0
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_F1,           // 0xF1
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_F2,           // 0xF2
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_F3,           // 0xF3
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_F4,           // 0xF4
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_F5,           // 0xF5
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_F6,           // 0xF6
    CEC_UCC_INVALID,  // BOSE_SPECIAL_FEATURE_4,     // 0xF7
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_F8,           // 0xF8
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_F9,           // 0xF9
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_FA,           // 0xFA
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_FB,           // 0xFB
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_FC,           // 0xFC
    CEC_UCC_INVALID,  // KEY_VAL_AVAIL_FD,           // 0xFD
    CEC_UCC_INVALID,  // BOSE_ASSERT_MUTE,           // 0xFE
    CEC_UCC_INVALID,  // BOSE_INVALID_KEY,           // 0xFF
};

static const KEY_VALUE BOSE_KEY_CEC_MAPPING[] =
{
    BOSE_ENTER,  // CEC_UCC_SELECT
    BOSE_UP_ARROW,  // CEC_UCC_UP
    BOSE_DOWN_ARROW,  // CEC_UCC_DOWN
    BOSE_LEFT_ARROW,  // CEC_UCC_LEFT
    BOSE_RIGHT_ARROW,  // CEC_UCC_RIGHT
    BOSE_INVALID_KEY,  // CEC_UCC_RIGHT_UP
    BOSE_INVALID_KEY,  // CEC_UCC_RIGHT_DOWN
    BOSE_INVALID_KEY,  // CEC_UCC_LEFT_UP
    BOSE_INVALID_KEY,  // CEC_UCC_LEFT_DOWN
    BOSE_I_TV,  // CEC_UCC_ROOT_MENU
    BOSE_TELETEXT,  // CEC_UCC_SETUP_MENU
    BOSE_DVD_MENU,  // CEC_UCC_CONTENTS_MENU
    BOSE_MORE_SOFTKEY_FAVORITE,  // CEC_UCC_FAVORITE_MENU
    BOSE_EXIT,  // CEC_UCC_EXIT
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED14
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED15
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED16
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED17
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED18
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED19
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED20
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED21
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED22
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED23
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED24
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED25
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED26
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED27
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED28
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED29
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED30
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED31
    BOSE_NUMBER_0,  // CEC_UCC_0
    BOSE_NUMBER_1,  // CEC_UCC_1 = 0x21,
    BOSE_NUMBER_2,  // CEC_UCC_2 = 0x22,
    BOSE_NUMBER_3,  // CEC_UCC_3 = 0x23,
    BOSE_NUMBER_4,  // CEC_UCC_4 = 0x24,
    BOSE_NUMBER_5,  // CEC_UCC_5 = 0x25,
    BOSE_NUMBER_6,  // CEC_UCC_6 = 0x26,
    BOSE_NUMBER_7,  // CEC_UCC_7 = 0x27,
    BOSE_NUMBER_8,  // CEC_UCC_8 = 0x28,
    BOSE_NUMBER_9,  // CEC_UCC_9 = 0x29,
    BOSE_DASH,  // CEC_UCC_DOT
    BOSE_ENTER,  // CEC_UCC_ENTER
    BOSE_INVALID_KEY,  // CEC_UCC_CLEAR
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED45
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED46
    BOSE_INVALID_KEY,  // CEC_UCC_NEXT_FAVORITE
    BOSE_CHANNEL_PRESET_UP,  // CEC_UCC_CHANNEL_UP
    BOSE_CHANNEL_PRESET_DOWN,  // CEC_UCC_CHANNEL_DOWN
    BOSE_LAST_CHANNEL,  // CEC_UCC_PREVIOUS_CHANNEL
    BOSE_INVALID_KEY,  // CEC_UCC_SOUND_SELECT
    BOSE_INVALID_KEY,  // CEC_UCC_INPUT_SELECT
    BOSE_INFO,  // CEC_UCC_DISPLAY_INFORMATION
    BOSE_INVALID_KEY,  // CEC_UCC_HELP
    BOSE_PAGE_UP,  // CEC_UCC_PAGE_UP
    BOSE_PAGE_DOWN,  // CEC_UCC_PAGE_DOWN
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED57
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED58
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED59
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED60
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED61
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED62
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED63
    BOSE_MORE_SOFTKEY_PWRTOGGLE,  // BOSE_ON_OFF,      //CEC_UCC_POWER
    BOSE_VOLUME_UP,  // CEC_UCC_VOLUME_UP
    BOSE_VOLUME_DOWN,  // CEC_UCC_VOLUME_DOWN
    BOSE_MUTE,  // CEC_UCC_MUTE
    BOSE_PLAY,  // CEC_UCC_PLAY
    BOSE_STOP,  // CEC_UCC_STOP
    BOSE_PAUSE,  // CEC_UCC_PAUSE
    BOSE_RECORD,  // CEC_UCC_RECORD
    BOSE_FAST_REVERSE,  // CEC_UCC_REWIND
    BOSE_FAST_FORWARD,  // CEC_UCC_FAST_FORWARD = 0x49,
    BOSE_INVALID_KEY,  // CEC_UCC_EJECT
    BOSE_QUICK_SKIP,  // CEC_UCC_FORWARD
    BOSE_QUICK_REPLAY,  // CEC_UCC_BACKWARD
    BOSE_INVALID_KEY,  // CEC_UCC_STOP_RECORD
    BOSE_INVALID_KEY,  // CEC_UCC_PAUSE_RECORD
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED79
    BOSE_INVALID_KEY,  // CEC_UCC_ANGLE = 0x50,
    BOSE_INVALID_KEY,  // CEC_UCC_SUB_PICTURE = 0x51,
    BOSE_I_TV,  // CEC_UCC_ROOT_MENU
    BOSE_INVALID_KEY,  // CEC_UCC_ELECTRONIC_PRORAM_GUIDE
    BOSE_INVALID_KEY,  // CEC_UCC_TIMER_PROGRAMMING = 0x54,
    BOSE_INVALID_KEY,  // CEC_UCC_INITAL_CONFIGURATION = 0x55,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED80 = 0x56,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED81 = 0x57,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED82 = 0x58,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED83 = 0x59,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED84 = 0x5A,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED85 = 0x5B,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED86 = 0x5C,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED87 = 0x5D,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED88 = 0x5E,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED89 = 0x5F,
    BOSE_INVALID_KEY,  // CEC_UCC_PLAY_FUNCTION = 0x60,
    BOSE_INVALID_KEY,  // CEC_UCC_PAUSE_PLAY_FUNCTION = 0x61,
    BOSE_INVALID_KEY,  // CEC_UCC_RECORD_FUNCTION = 0x62,
    BOSE_INVALID_KEY,  // CEC_UCC_PAUSE_RECORD_FUNCTION = 0x63,
    BOSE_INVALID_KEY,  // CEC_UCC_STOP_FUNCTION = 0x64,
    BOSE_INVALID_KEY,  // CEC_UCC_MUTE_FUNCTION = 0x65,
    BOSE_INVALID_KEY,  // CEC_UCC_RESTORE_VOLUME_FUNCTION = 0x66,
    BOSE_INVALID_KEY,  // CEC_UCC_TUNE_FUNCTION = 0x67,
    BOSE_INVALID_KEY,  // CEC_UCC_SELECT_TUNE_FUNCTION = 0x68,
    BOSE_INVALID_KEY,  // CEC_UCC_SELECT_AV_INPUT_FUNCTION = 0x69,
    BOSE_INVALID_KEY,  // CEC_UCC_SELECT_AUDIO_INPUT_FUNCTION = 0x6A,
    BOSE_INVALID_KEY,  // CEC_UCC_POWER_TOGGLE_FUNCTION = 0x6B,
    BOSE_INVALID_KEY,  // CEC_UCC_POWER_OFF_FUNCTION = 0x6C,
    BOSE_INVALID_KEY,  // CEC_UCC_POWER_ON_FUNCTION = 0x6D,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED110 = 0x6E,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED111 = 0x6F,
    BOSE_INVALID_KEY,  // CEC_UCC_RESERVED112 = 0x70,
    BOSE_RED,  // CEC_UCC_F2_RED
    BOSE_BLUE,  // CEC_UCC_F1_BLUE
    BOSE_GREEN,  // CEC_UCC_F3_GREEN
    BOSE_YELLOW,  // CEC_UCC_F4_YELLOW
    BOSE_INVALID_KEY,  // CEC_UCC_F5 = 0x75,
    BOSE_INVALID_KEY,  // CEC_UCC_DATA = 0x76
    BOSE_INVALID_KEY,  // CEC_UCC_INVALID = 0xFF,
    /* 0x77 - 0xFF RESERVED */
};

#define CEC_DEFAULT_MORE_MENU_ITEMS (  \
              FAVORITE_SOFTKEY_BIT | \
              PWRTOGGLE_SOFTKEY_BIT )
#endif
