#ifndef PRODUCT_EXT_FLASH_MAP_H
#define PRODUCT_EXT_FLASH_MAP_H

// Update Storage
#define EXT_FLASH_ADDR_UPDATE_STORAGE_START     0x00000000
#define EXT_FLASH_ADDR_UPDATE_STORAGE_END       0x00300000
#define EXT_FLASH_UPDATE_STORAGE_LENGTH         (EXT_FLASH_ADDR_UPDATE_STORAGE_END-EXT_FLASH_ADDR_UPDATE_STORAGE_START)

// System Params
#define EXT_FLASH_ADDR_SYS_PARAMS_START         0x003B0000
#define EXT_FLASH_ADDR_SYS_PARAMS_END           0x003C0000
#define EXT_FLASH_SYS_PARAMS_LENGTH             (EXT_FLASH_ADDR_SYS_PARAMS_END-EXT_FLASH_ADDR_SYS_PARAMS_START)

// Animations
#define EXT_FLASH_ADDR_ANIMATIONS_START         0x003C0000
#define EXT_FLASH_ADDR_ANIMATIONS_END           0x00400000
#define EXT_FLASH_ANIMATIONS_LENGTH             (EXT_FLASH_ADDR_ANIMATIONS_END-EXT_FLASH_ADDR_ANIMATIONS_START)

#endif // PRODUCT_EXT_FLASH_MAP_H
