/*
 *
 * @author Shelby Apps Team
 *
 * @attention
 *     BOSE CORPORATION.
 *     COPYRIGHT 2017 BOSE CORPORATION ALL RIGHTS RESERVED.
 *     This program may not be reproduced, in whole or in part in any
 *     form or any means whatsoever without the written permission of:
 *         BOSE CORPORATION
 *         The Mountain,
 *         Framingham, MA 01701-9168
 */

#ifndef PSOCCOMMS_H_
#define PSOCCOMMS_H_

typedef enum {
    PSOC_COMMS_COMMAND_GETVERSION = 0,
    PSOC_COMMS_COMMAND_LEDS_CLEARALL,
    PSOC_COMMS_COMMAND_LEDS_SETALL,
    PSOC_COMMS_COMMAND_LEDS_SETONE,
    PSOC_COMMS_COMMAND_ANIMATION_LOADSTART,
    PSOC_COMMS_COMMAND_ANIMATION_LOADPATTERN,
    PSOC_COMMS_COMMAND_ANIMATION_START,
    PSOC_COMMS_COMMAND_ANIMATION_STOPIMMEDIATE,
    PSOC_COMMS_COMMAND_ANIMATION_STOPATEND,
    PSOC_COMMS_COMMAND_ANIMATION_RESUME,
    PSOC_COMMS_COMMAND_INVALID,
} PSoCCommsCommand_t;

typedef enum {
    PSOC_COMMS_RESPONSE_STATUS = 0,
    PSOC_COMMS_RESPONSE_VERSION,
    PSOC_COMMS_RESPONSE_SLIDER,
    PSOC_COMMS_RESPONSE_BUTTON,
    PSOC_COMMS_RESPONSE_ANIMATION_STARTED,
    PSOC_COMMS_RESPONSE_ANIMATION_STOPPED,
    PSOC_COMMS_RESPONSE_INVALID,
} PSoCCommsResponse_t;

#define PSOC_COMMS_STATUS_FAILURE 0
#define PSOC_COMMS_STATUS_SUCCESS 1

#define PSOC_COMMS_FROM_PSOC_BUFFER_SIZE 6 // Outgoing buffer size is fixed
#define PSOC_COMMS_TO_PSOC_BUFFER_SIZE 64 // Max command buffer size

#endif /* PSOCCOMMS_H_ */
