#ifndef BOSELINKMESSAGES_H
#define BOSELINKMESSAGES_H

typedef enum
{
SPOKEN_LANGUAGE_ENGLISH,
SPOKEN_LANUGAGE_SPANISH,
SPOKEN_LANGUAGE_FRENCH,
SPOKEN_LANGUAGE_DANISH,
SPOKEN_LANGUAGE_GERMAN,
SPOKEN_LANGUAGE_ITALIAN,
SPOKEN_LANGUAGE_SWEDISH,
SPOKEN_LANGUAGE_POLISH,
SPOKEN_LANGUAGE_HUNGARIAN,
SPOKEN_LANGUAGE_FINNISH,
SPOKEN_LANGUAGE_CZECH,
SPOKEN_LANGUAGE_GREEK,
SPOKEN_LANGUAGE_NORWEGIAN,
SPOKEN_LANGUAGE_PORTUGUESE,
SPOKEN_LANGUAGE_ROMANIAN,
SPOKEN_LANGUAGE_RUSSIAN,
SPOKEN_LANGUAGE_SLOVENIAN,
SPOKEN_LANGUAGE_TURKISH,
SPOKEN_LANGUAGE_MANDARIN_CHINESE,
SPOKEN_LANGUAGE_THAI,
SPOKEN_LANGUAGE_KOREAN,
SPOKEN_LANGUAGE_CANTONESE_CHINESE,
SPOKEN_LANGUAGE_HEBREW,
SPOKEN_LANGUAGE_ARABIC,
SPOKEN_LANGUAGE_JAPANESE,
SPOKEN_LANGUAGE_DUTCH,
SPOKEN_LANGUAGE_NUM,
SPOKEN_LANGUAGE_UNDEFINED = 0xff,
} SPOKEN_LANGUAGE;

typedef enum
{
    SPEAKER_REGION_US_AIM = 0x00,
    SPEAKER_REGION_EUROPE = 0x01,
    SPEAKER_REGION_JAPAN  = 0x02,
    SPEAKER_REGION_AP     = 0x03,
} SPEAKER_REGION;

#pragma pack()

#endif // BOSELINKMESSAGES_H
