#ifndef PRODUCT_MEMORY_MAP_H
#define PRODUCT_MEMORY_MAP_H

#include "internalFlash_STM32F205VG.h"

/*
REGION          START        SIZE           KB   SECTOR(S)
Bootloader      0x08000000   0x00008000     32       0-1
Mftg Params     0x08008000   0x00004000     16       2
Application     0x0800C000   0x00074000    464       3-7
Diags           0x08080000   0x00080000    512       8-11
*/

/* Internal Flash Map */
#define INTERNAL_FLASH_BOOTLOADER_START          INTERNAL_FLASH_SECTOR0_START_ADDRESS
#define INTERNAL_FLASH_BOOTLOADER_END            INTERNAL_FLASH_SECTOR1_END_ADDRESS

#define INTERNAL_FLASH_MANUFACTURING_START       INTERNAL_FLASH_SECTOR2_START_ADDRESS
#define INTERNAL_FLASH_MANUFACTURING_END         INTERNAL_FLASH_SECTOR2_END_ADDRESS

#define INTERNAL_FLASH_APPLICATION_START         INTERNAL_FLASH_SECTOR3_START_ADDRESS
#define INTERNAL_FLASH_APPLICATION_END           INTERNAL_FLASH_SECTOR7_END_ADDRESS

#define INTERNAL_FLASH_RECOVERY_IMG_START        INTERNAL_FLASH_SECTOR8_START_ADDRESS
#define INTERNAL_FLASH_RECOVERY_IMG_END          INTERNAL_FLASH_SECTOR11_END_ADDRESS

#endif // PRODUCT_MEMORY_MAP_H
